# Generated by Django 4.0.6 on 2022-07-15 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='semester',
            name='cr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', related_query_name='has_semester', to=settings.AUTH_USER_MODEL, validators=[webapp.validators.validate_student]),
        ),
    ]
