# Generated by Django 4.0.6 on 2022-07-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_customuser_is_student_alter_semester_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester', related_query_name='has_semester', to='webapp.department'),
            preserve_default=False,
        ),
    ]
