# Generated by Django 4.0.6 on 2022-07-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_semester_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('happenning', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('due_date',)},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'College'},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assigned_on',
            new_name='assigned_at',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', related_query_name='has_student', to='webapp.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='cr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, validators=[webapp.validators.validate_student]),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('discord_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('member', models.ManyToManyField(related_name='club', related_query_name='has_club', to=settings.AUTH_USER_MODEL)),
                ('president', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
