# Generated by Django 4.0.6 on 2022-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_event_alter_assignment_options_alter_college_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/%d/'),
        ),
    ]
