# Generated by Django 4.0.6 on 2022-07-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_assignment_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='head',
            new_name='hod',
        ),
    ]
