# Generated by Django 4.0.6 on 2022-07-15 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_submittedby_rename_member_club_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedby',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted_by',
            field=models.ManyToManyField(related_name='assignment', related_query_name='has_assignment', through='webapp.SubmittedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
