# Generated by Django 4.0.6 on 2022-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_submittedby_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
    ]
