# Generated by Django 4.0.6 on 2022-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_assignment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuerySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='happenning',
            new_name='happening',
        ),
    ]
