# Generated by Django 4.0.6 on 2022-07-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_eventqueryset_rename_happenning_event_happening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, validators=[webapp.validators.validate_teacher]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('topic'), django.db.models.expressions.F('semester'), django.db.models.expressions.F('teacher'), name='unique_semester_topic_teacher'),
        ),
    ]
