# Generated by Django 4.0.6 on 2022-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_assignment_teacher_alter_assignment_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='images/events/%Y-%m-%d'),
        ),
    ]
