# Generated by Django 4.0.6 on 2022-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_college_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedby',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Checked'), ('r', 'Rejected')], default='p', max_length=1),
        ),
    ]
