# Generated by Django 4.0.6 on 2022-07-16 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_submittedby_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('discussed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion', related_query_name='has_discussion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-discussed_at',),
            },
        ),
    ]
