# Generated by Django 4.0.6 on 2022-07-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='student',
            new_name='user',
        ),
    ]
