# Generated by Django 4.0.6 on 2022-07-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_rename_student_discussion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', related_query_name='has_discussion', to='webapp.semester'),
            preserve_default=False,
        ),
    ]
