# Generated by Django 4.0.6 on 2022-07-16 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_discussion_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ('discussed_at',)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', related_query_name='has_student', to='webapp.semester'),
        ),
    ]
