# Generated by Django 4.0.6 on 2022-07-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_assignment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='assignments/%Y-%m-%d')),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('c', 'Checked'), ('r', 'Rejected')], default='p', max_length=1)),
                ('submitted_at', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('submitted_at',),
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='SubmittedBy',
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', related_query_name='has_submission', to=settings.AUTH_USER_MODEL, validators=[webapp.validators.validate_student]),
        ),
    ]
