# Generated by Django 4.0.6 on 2022-07-16 08:17

from django.db import migrations, models
import django.db.models.deletion
import webapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_submission_remove_assignment_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.utils.upload_directory_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', related_query_name='has_submission', to='webapp.assignment'),
        ),
    ]
